name: Mono-Repo CI Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [service-1, service-2, service-3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        working-directory: ./packages/${{ matrix.service }}

  test:
    name: Test Job
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        service: [service-1, service-2, service-3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npm run test
          npm run test:int

  lint:
    name: Lint Job
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        service: [service-1, service-2, service-3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run lint
        working-directory: ./packages/${{ matrix.service }}

  security-scan:
    name: Security Scan Job
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: javascript-typescript
            build-mode: none
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:${{matrix.language}}'

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: security-scan
    strategy:
      matrix:
        service: [service-1, service-2, service-3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: npm run deploy
        working-directory: ./packages/${{ matrix.service }}
